### PR TITLE
nugetized build

### PR DESCRIPTION
**Pull request by et1975**
@alfonsogarciacaro 
Fairly manual build/publish, but should work.

### CODE REVIEW

**Comment by et1975** [comment]
Could someone review and publish the nuget please?

**Comment by alfonsogarciacaro** [comment]
Will do! Thank you and sorry for the late response 😅

**Comment by alfonsogarciacaro** [comment]
Fable.Import.Express 0.1.0 has been published but please note it has a dependency on the new Fable.Import.Node package. To use it you will need the new dotnet-fable 1.1 that I'm going to publish in a short moment :+1:

**Comment by et1975** [comment]
Sorry, I'm confused, I can see that the published package depends on node import, but where is the dependency listed in the sources? The code I see here still depends on fable 1.0, did you publish the updated sources somewhere?

**Comment by alfonsogarciacaro** [comment]
@et1975 Sorry for the confusion. At the moment I'm releasing packages like this:

- Fable.Core/dotnet-fable 1.0.x: These still have browser and node bindings in Fable.Core. They should be prereleases but I messed up the versioning and I had to start publishing 1.0.x versions.
- Fable.Core/dotnet fable 1.1.0-rc-x: These have browser and node bindings split from Fable.Core. Paket won't download them unless you use the prerelease option.

Again, sorry for the confusion. As soon as we update the other libraries we can push Fable 1.1 and keep on with that.

**Pull request merged**
